name: PR Pipeline
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions: write-all
env:
  nuget-username: chrisxpr
  src-dir: ./src/code
  coverage-threshold: 0
  repo-organisation: architected
  team-pat: ${{ secrets.NUGET_PAT}}
concurrency: alpha-${{ github.ref}}
jobs:
  dotnetBuild:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: buildAndTest
        uses: devperimental/composite-action-library/dotnet-build-and-test@v4
        with:
          nuget-username: ${{ env.nuget-username }}
          src-dir: ${{ env.src-dir }}
          coverage-threshold: ${{ env.coverage-threshold }}
          repo-organisation: ${{ env.repo-organisation }}
          team-pat: ${{ env.team-pat }}
  codereview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AICodeReviewer
        uses: devperimental/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.OPEN_API_KEY }} 
          OPENAI_API_MODEL: gpt-4
          exclude: "**/*.json, **/*.md,yarn.lock,dist/**,.github/**,**/*.dll,**/*.pdb,**/*.exe"